replicaCount: 1

image: 
  repository: "bradmccoydev/terraform-plan-validator"
  tag: "84fd740fd7761db1263553674bec8ec8d88cbae3"
  pullPolicy: Always

  publicUrl: "bradmccoydev.io"

nameOverride: ''
fullnameOverride: ''

service:
  annotation: {}
  type: NodePort
  port: 80

ingress:
  enabled: true
  hostname: bradmccoydev.io
  path: /
  annotations: {}
  tls:
    enabled: true
    secretName: ""

resources: 
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi


nodeSelector: {}

tolerations: []

antiAffinity:
  enabled: true


app:
  initialDelaySeconds: 10
  periodSeconds: 10
  successsThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5

  